# Generated by Django 2.2.5 on 2022-05-04 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileReg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=200)),
                ('about', models.TextField()),
                ('image', models.ImageField(default='default.jpg', upload_to='uploads/pics')),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
