# Generated by Django 2.2.5 on 2022-05-11 22:47

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0002_blog_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title2',
            field=tinymce.models.HTMLField(),
        ),
    ]
